### ISSUE TITLE
onChangePublicPorts parameter checking scope

### ISSUE THREAD

**Issue by unixninja92** [007pig/plugin-UPnP2#1]
In onChangePublicPorts you have an if statement checking if the ports parameter has anything in it, but it seems almost useless only having it around the small amount of code it's around rather than most of the code in the method. It looks to me like you should either remove it or have it encompass most of the code in the method. 
https://github.com/007pig/plugin-UPnP2/blob/master/src/main/java/plugins/UPnP2/UPnP2.java#L115-L119

**Comment by 007pig** [comment]
Looks like it's impossible for ports to be empty, so I just removed the check.
